"""update_seccion_add_anio_academico_tipo_grupo_numero_estudiantes

Revision ID: 3dc2453812ae
Revises: c7d8e9f0a1b2
Create Date: 2025-11-19 13:23:59.765086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc2453812ae'
down_revision: Union[str, Sequence[str], None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignatura', sa.Column('horas_presenciales', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('asignatura', sa.Column('horas_mixtas', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('asignatura', sa.Column('horas_autonomas', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('asignatura', sa.Column('cantidad_creditos', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('asignatura', sa.Column('semestre', sa.Integer(), nullable=False, server_default='1'))
    
    # Migrar creditos a cantidad_creditos
    op.execute("UPDATE asignatura SET cantidad_creditos = COALESCE(creditos, 0)")
    
    op.drop_column('asignatura', 'creditos')
    
    # Remover server_default después de migrar
    op.alter_column('asignatura', 'horas_presenciales', server_default=None)
    op.alter_column('asignatura', 'horas_mixtas', server_default=None)
    op.alter_column('asignatura', 'horas_autonomas', server_default=None)
    op.alter_column('asignatura', 'cantidad_creditos', server_default=None)
    op.alter_column('asignatura', 'semestre', server_default=None)
    
    op.alter_column('clase', 'docente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('clase_docente_id_fkey'), 'clase', type_='foreignkey')
    op.create_foreign_key(None, 'clase', 'docente', ['docente_id'], ['user_id'])
    op.drop_index(op.f('ix_evento_activo'), table_name='evento')
    op.drop_index(op.f('ix_evento_clase_id'), table_name='evento')
    op.drop_index(op.f('ix_evento_created_at'), table_name='evento')
    op.drop_index(op.f('ix_evento_docente_id'), table_name='evento')
    op.drop_constraint(op.f('evento_docente_id_fkey'), 'evento', type_='foreignkey')
    op.create_foreign_key(None, 'evento', 'docente', ['docente_id'], ['user_id'])
    op.alter_column('restriccion', 'docente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('restriccion_docente_id_fkey'), 'restriccion', type_='foreignkey')
    op.create_foreign_key(None, 'restriccion', 'docente', ['docente_id'], ['user_id'])
    op.alter_column('restriccion_horario', 'docente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('restriccion_horario_docente_id_fkey'), 'restriccion_horario', type_='foreignkey')
    op.create_foreign_key(None, 'restriccion_horario', 'docente', ['docente_id'], ['user_id'])
    
    # Agregar columnas temporales permitiendo NULL
    op.add_column('seccion', sa.Column('anio_academico', sa.Integer(), nullable=True))
    op.add_column('seccion', sa.Column('tipo_grupo', sa.String(length=20), nullable=True))
    op.add_column('seccion', sa.Column('numero_estudiantes', sa.Integer(), nullable=True))
    
    # Migrar datos existentes: copiar anio a anio_academico
    op.execute("UPDATE seccion SET anio_academico = COALESCE(anio, 1)")
    op.execute("UPDATE seccion SET tipo_grupo = 'seccion'")
    op.execute("UPDATE seccion SET numero_estudiantes = COALESCE(cupos, 30)")
    
    # Hacer NOT NULL después de migrar
    op.alter_column('seccion', 'anio_academico', nullable=False)
    op.alter_column('seccion', 'tipo_grupo', nullable=False)
    op.alter_column('seccion', 'numero_estudiantes', nullable=False)
    
    op.drop_column('seccion', 'anio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seccion', sa.Column('anio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('seccion', 'numero_estudiantes')
    op.drop_column('seccion', 'tipo_grupo')
    op.drop_column('seccion', 'anio_academico')
    op.drop_constraint(None, 'restriccion_horario', type_='foreignkey')
    op.create_foreign_key(op.f('restriccion_horario_docente_id_fkey'), 'restriccion_horario', 'docente', ['docente_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('restriccion_horario', 'docente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'restriccion', type_='foreignkey')
    op.create_foreign_key(op.f('restriccion_docente_id_fkey'), 'restriccion', 'docente', ['docente_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('restriccion', 'docente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'evento', type_='foreignkey')
    op.create_foreign_key(op.f('evento_docente_id_fkey'), 'evento', 'docente', ['docente_id'], ['user_id'], ondelete='CASCADE')
    op.create_index(op.f('ix_evento_docente_id'), 'evento', ['docente_id'], unique=False)
    op.create_index(op.f('ix_evento_created_at'), 'evento', ['created_at'], unique=False)
    op.create_index(op.f('ix_evento_clase_id'), 'evento', ['clase_id'], unique=False)
    op.create_index(op.f('ix_evento_activo'), 'evento', ['activo'], unique=False)
    op.drop_constraint(None, 'clase', type_='foreignkey')
    op.create_foreign_key(op.f('clase_docente_id_fkey'), 'clase', 'docente', ['docente_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('clase', 'docente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('asignatura', sa.Column('creditos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('asignatura', 'semestre')
    op.drop_column('asignatura', 'cantidad_creditos')
    op.drop_column('asignatura', 'horas_autonomas')
    op.drop_column('asignatura', 'horas_mixtas')
    op.drop_column('asignatura', 'horas_presenciales')
    # ### end Alembic commands ###
