from typing import Protocol, Optional, List
from uuid import UUID
from .entities import Product

class ProductRepositoryPort(Protocol):
    def add(self, product: Product) -> Product: ...
    def get(self, product_id: UUID) -> Optional[Product]: ...
    def list(self) -> List[Product]: ...
