from typing import Protocol, Optional, List
from uuid import UUID
from .entities import User

class UserRepositoryPort(Protocol):
    def add(self, user: User) -> User: ...
    def get(self, user_id: UUID) -> Optional[User]: ...
    def get_by_username(self, username: str) -> Optional[User]: ...
    def list(self) -> List[User]: ...
